### PR TITLE
Refactor out use of anyhow

### PR DESCRIPTION
**Pull request by algesten**
This is part of work spanning all the webrtc crates: https://github.com/webrtc-rs/webrtc/issues/106

### CODE REVIEW

**Comment by algesten** [comment]
First stab at this, and I have some thinking to do before considering it done:

> * Whether to keep or not keep a `type Result<T> = std::error::Result<T, Error>` per crate or not. It often gets messy.

Yes. I will use this strictly in the local crate.

> * Do the sub-error enums help or not? I'm leaning towards getting rid of them and merging all in one enum.

Gone. Just one error type.

> * Whether to strictly require `PartialEq` on all errors – there was only one test relying on it here, but that could be useful in the future. Specifically this is a problem when wrapping stuff like `io::Error`, which doesn't implement equality.

Fixed by making a newtype for io::Error.

**Comment by rainliu** [comment]
look good to me for this Error handling refactoring for this sdp crate.

Please publish your PR in order to get it merged.

Thanks.

**Comment by algesten** [comment]
It's marked as ready to merge.

**Comment by rainliu** [comment]
@algesten, any other PR for sdp crate?

If no other PRs, I will upgrade it to v0.3.0 (due to this breaking change).

**Comment by algesten** [comment]
@rainliu I believe the sdp crate is finished.

But I'm on the fence of how practically bring this anyhow change out in a way that makes all the crates compatible. It's quite tough to work with the separate git repos.

I'm thinking I might change all the `crates/*/Cargo.toml` to use `path="../"` style references so I can ensure the entire tree compiles.

What I want to avoid is upgrading say sdp to 0.3.0, just to later realize I needed to do even more breaking changes.

**Comment by algesten** [comment]
I also don't want to block other work in webrtc-rs. If we say release the util crate, there are quite a few breaking changes with the other crates, it effectively becomes a blocker for the entire project.

**Pull request merged**
